NumPy



In [3]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# make tuple
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# dimensionsions in array

# 0-D arrays
import numpy as np
arr=np.array(42)
print(arr)

42


In [6]:
# 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3-D arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


CHECK NUMBER OF DIMENSIONS


In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [19]:
# Higher Dimensional Arrays

import numpy as np  
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


NUMPY INDEXING


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1]+arr[3])

1
6


In [22]:
# Access 2-D Arrays
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])  # Access element at row 0, column 1


2


In [23]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0,0,1])

2


ARRAY SLICING

In [30]:
# Slicing in python means taking elements from one given index to another given index.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])  # elements from index 1 to index 4
print(arr[:4])   # elements from index 0 to index 3
print(arr[4:])   # elements from index 4 to the end
print(arr[-3:-1])  # elements from index -3 to index -2
print(arr[1:5:2])  # elements from index 1 to index 4 with step 2



[2 3 4 5]
[1 2 3 4]
[5 6 7]
[5 6]
[2 4]


DATA TYPES


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [32]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [34]:
import numpy as np 
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr.dtype)

|S1


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


COPY VS VIEW 

In [44]:
import numpy as np
arr= np.array([1, 2, 3, 4])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


Check if Array Owns its Data


In [ ]:
# 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

# he copy returns None.
# The view returns the original array

None
[1 2 3 4 5]


ARRAY SHAPE

In [50]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr.shape)


(1, 1, 1, 1, 4)


NumPy Array Reshaping


In [54]:
# Reshaping means changing the shape of an array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr=arr.reshape(4, 3)
print(newarr)   


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
# Reshape From 1-D to 3-D

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


NumPy Array Iterating


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
        print(x)

1
2
3


In [ ]:
# Iterate on each scalar element of the 2-D array:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)


1
2
3
4
5
6


In [67]:
# Iterating 3-D Arrays
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [68]:
#Iterating Array With Different Data Types

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)



np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


NumPy Joining Array


In [69]:
# Joining means putting contents of two or more arrays in a single array.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
# Joining Arrays Using Stack Functions

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

In [70]:
# Stacking Along Rows

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


NumPy Splitting Array


In [72]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr=np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [76]:
# Splitting 2-D Arrays
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [81]:
# searching arrays

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.where(arr==4)
print(x)

(array([3]),)


Search Sorted


In [84]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x=np.searchsorted(arr, 7)
print(x)


1


In [86]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x=np.searchsorted(arr,7,side='right')
print(x)

2


In [88]:
# search sorted()
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


Accessing and Modifying Array Elements



In [90]:
a= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

a[0, 3]  # Access element at first row, fourth column
a[1, 4]  # Access element at second row, fifth column
a[0, 4] = 50  # Change value at first row, fifth column to 50

NumPy Sorting Arrays


In [91]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [92]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [93]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [94]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


NumPy Filter Array


In [95]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]
